---
- secret:
    name: SECRET_E2E_TESTS
    data:
      KUBECONFIG: !encrypted/pkcs1-oaep
        - JNzhfBK6edAYWM9UyhnBeRozpySlYZCu/jrcbjJUXwpd6mTNnMKuVBcsMxdwlcb/sJCrg
          ZDtrOX7DyOaf7hYxixHrxOWsztXVUDxiVP1o/HP60CbQmaKml2nZRAlAZ6EoZcC80DI+8
          x6JkpDZCDs3PsFZ09ubLT7OukzTE2nIjq1sQSOg2M74/eOBxpokfMFvjSUhRKS61dLig4
          j4f1mVkd9s4O0h7di5LfAwTLvEOTjKsG9TUSz+EGs3mUnaSR39zcp4nNa3Z0a4/X3sBHZ
          lZDorvRlQpr8sK398RSu0KbGeofCdDAGQRoT2Cdz9QqbTYl9g4mxPUyDB+a6CBLhztJft
          /c2CoazSgxE28vHw6rywQyHMxsCU5JqdK37nRR18UFzNLFHy1AjfRlSWGh6Yh4han5M9z
          0KYRqUt8pps0COiliz50Fot286jcwa7bpoeKxvYmhqCaDcLgdxVbx3/y9mcLkW+btQMWI
          oTdANP3943lJEDFLhu/SsFLZ5jm1aw184HbohXaWW6otQnusDlduuMQ+0tKrAh8xEDWGx
          RxueyFiKR1Wan8mt199BbjV2XagPWErp3+3UWdv2CZ0Meg4GI6BO96Z2lpWT6gefo9+WH
          EYAZ/j1brCeP8NnbOxaMIrMDme6rBOpFB+Q2VEGOjQ0uPb3hJhsdeIlCut6ofQ=
        - ajBKMizjlhfelItsWqCZVEW7uJqgxAbHIbCZga24pQWagrIOaWTYQndamoj3HtBmel71g
          b6wJEjk3NxsVgxheNida/BhQGYproDsSvZFO0B6+HDpq/ktlcO4QJOfDspA/bCXyceosb
          xSh3SWkFfUSr5jN72OjkefEQ7K3bPLCZPmWhgvhgp3AmIZd2HFobLb2T/MWFpzAhnqlGY
          4R/u8cPfpaACuNhjkh/SVvdhHZnuIGy0GYOOHEbRaobtQ0HTvuo1fBjHayD0CjXhPaifr
          gokA6YOGKv55Pk659J/GiSuwVWD5VJ+daAblzXZt/KJKECyQ3BtOJNjfi6c+/13OFSEae
          lhukF8F6Ch3za/LC50Thf1bbpIkOqeurtRWhsvJnuGabnRoqbs5ZUWREdwv2qczyVQEtN
          EGKggsaWjQafAK8erl55maeJcvjJhOR27wRPZ2g8IpR8rUCiXh/9ST2miWI9KMhB4yLsU
          HL4ycTPyS4ljM0nLemI+tHE0UM6uq+Pw3heQkzzARYDQaeEBPd+kOtCTwTFm+Yx6PIfzV
          gwZaEsDqJCiQlLBzvaudOxk/4nBUDiwJIHmaWNkuWKwD5XsXWWE3Xn++mYWxgD2WsWQvg
          fVsrIzNUK+DfeBkyGRZQhGpmpXT4V1mat0F7zA984CMsGHBzAjvWl5+pL68peQ=
        - G278RlDmklOWB5rdOxkyhPZV9bpDiuOng1S1ahlsM8DxIkzSmRYhOvJ28FrrrmTZMt8Hz
          HBxpxgGeFeLopPho71MIsyN9YCv8uhMfhzLr60wA/B3QkrU8CpjSvtPDh3ncZALm3SMYz
          Hxe9blx8E5iZmJ5C9yIMoE6hpqOjkDm9o+ZKWOwQOATaLsfdNI0mBjrYSPJz/PeENk5Fs
          CFcSHYvcmcaGdll8ETgoiSOjO+dRzci3FtqX4srw9tUktIeBpA1RMRtu3QRZCkocxj75R
          Y5Y/5H8EyKcXyMaLHgAIXOBa0ixl+uSKW/8VezUzmCPDnWBK1+OIuMtkZIfIW+mYPuLKY
          GHIONrpE1G9fD+vgZYzBKyQv9kWYAPoqeh3xxx0pWdUd6Yw+d+pdRsEn/ws8jXrWgJGzQ
          DxXV4Ip2B6nVM1wa5LlHpCPVyRquzTun+4GEN7Un+ipsuv+zAj6qBIWXGNQD0QfYJkB8H
          BEgLfFokzAmicRAh2YJGd2dHXFWL31KhQq6jTlXoDckEpr5g/iMFf5c3y30Sp9KQviPF0
          wChIFtBoUvU/tY5Nbj16MMuxMZ+OXOvCswonpMPGvdgbsS2W9sW1aD6oqS1V2dstC6MWJ
          G2K2bHEzgDhHJZfx+zH292YkwKL0+3Vpi48Ob+No4iWRM9ld1e8+G1Bxpd/8dQ=
        - aCu1mJAoNDPAydL8OAagu929kDojePu1XWjSP7b6T8mLaVz2OCe8aPbLBEx5FtSGrQBk2
          QVXaQ0PsJNwheJguNE5HrGnlH3q/YC9gOQvBrRFDJ5LdGDhFD0csSrA42wniP+TFtwPLK
          9a2P8H12flMfpKVzUxAGSoLo45sPRRoWR0K83ws4NaTtO+kOTH7mzfzm9Zy2TsM7cCCSq
          nYlSe22OKi6XwWGfg5v6KDgwXKaI1Br5k7HYj2TsUQtjylmtFMdV70GBo5Sb6uOs5LkNI
          +if/DHzWZQn1kjIgrb56hvxvIEIJp00Df4TXG4wg62FHfaMSrLiG00CoeH0pLJtyjJldX
          zCiQcVakJROQmxlRauCnm9ZiXCXRCa5QfnD4APnfXsM5kI8/+oUF2/FVMqbxtoiyRQwCI
          JhxceWyiktU3N71pJILP0qnAvksN8gw1RXt7bfw0T0sBPziWdExXETAzdN5t+mL2hcgid
          wj3GEXyYcASRD9ZbcMFB9d2x8m3gSdrqvwGY5JGDo3XlKsyjPIEeYlhq6pki6nk+dCLWv
          bKcGb/CH3mtzQzikiZhGik1++kbr22W8sYlpftaoGkxz62E/Ejo+hdQZqRAcluat9x4+l
          nAQzBna0mK7gYvvwhcXQvM0ri200lDS+77WPCwNDQ8SjwAdwaEppFpJT6iWi1k=
        - Tc2H1cOPrET7wZ+ug6NQNGz7goVoG/A3QgKLoYaEbQSQxGIsJfb9gDn3v+WyFzQKYB4mX
          MFTtNsTE/sM1vsavH5lVhH5k03afGem1mYUPC8b8XyMCQIB685HgvCkCStar8pehckvqB
          eH7D8PA19tYdZZI2Lk73qWvGZyl64iZtevAx1eLVmdYTc61AdRMc+9sVJky90usL3lGDK
          MsIpA2YqoMzQa7kr5+4IStpAgXAznp3CgLtXLBIciUhD0bgXePrUaPJK1EsSXrihi840y
          DHJo7cmYTGSFD1CT+gYnWpPjBNXhhMJ64LApptBvSX/UZh9TLwJt68jiUuNcLzuJUeD4g
          gqV3R30HnuhlmxI07VQFZZtIdtY9u8F8NqDN1x97D+3FqmDz/fxb6lSjaKVf7vkzWW7Hp
          eYnM75vasa5MpFBoIzJHoSTKdBr292LwCIU74g0KejRfV6/RM88BBedAx0tE58/YLzbaq
          lBcyERGhAwO059or/wiBfQd5z0hDPW5gQTAwFesBcplqDNgCg+ypAeGGkk1eKfitWQC5p
          FXnLV8naSEdJFjLr5/5tT2NkOoi7rakHWWbOlPfjzwENH8Y+p82YaUtFmSfSq1xu8r4QR
          MvGcaEEnnKdBvo5bH2zWaD+auKLQdBJHFeFuxhKq5m0COrvwTw80PgmFtNLB4k=

- semaphore:
    name: semaphore-e2e-tests
    max: 1

- job:
    name: e2e-tests-gardener
    pre-run: playbooks/pre.yml
    run: playbooks/run.yml
    # post-run: playbooks/post.yml
    # cleanup-run: playbooks/cleanup.yml
    secrets:
      - name: secret
        secret: SECRET_E2E_TESTS

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - yamllint
    post:
      jobs:
        - e2e-tests-gardener
