---
- secret:
    name: SECRET_E2E_TESTS
    data:
      KUBECONFIG: !encrypted/pkcs1-oaep
        - QIxkOt0NGghNL5Busmo0TSpWFpSaJEmTuNJWLuoBBZkBOCsZMPZsaOMcU5XUkGMFEx6CL
          21qfaR7c/o1oJCsSNSq264Azc0tFb2TnbQtjW6WOQmU/nunTIPHtzUQmJZg/XdDzSfCuH
          3MKDQCUVueREb4A9M3XqNTI3fL29cPJP6rOJQ/LA+QYcgyKoQ11r9DeAHXfRpLq+QZZmr
          2bnYWdVVqfNa4T2yez31+smIpvqj/vjmNKJ0kKltmzsiIBqZPQiqs30GGvlYfuajoV6rP
          EyAOGGapH54Bd3gFiUE8C3bZHrAm9gnhdkaOFMPRwFMdgoVDnUoeeHnR7B83MTZ4bYkEh
          rFcCGw/diiyxnzoX4sSWNbYQWOKdwnU7UDYjdqsDoX1fFSD5xCz3DYgJPKtMMPikyQemu
          N+r9t/QDC9DULEa//9kVZZy8iCtD08ymHUG/Le7rY4V0Qk3f7YUzQ8R6Tu8n+6bmFFtyU
          zEZpBbDTS+Ey9RS094Wt0uU25mHn8Hlfz/b5Ji/04bFBuf1QrGFntwMNEC9NjDP9asIe7
          yWrcWqwH8FQ0v43q+6l0deGEIC2P4PZvX1PSN0Il/KZKFdPLZpudZXWUE+BofF5npTVFQ
          hy4+8lbkGFdhTBtRUKp8ay/4IElE8h5XnpiY39YcUcL4S5wK7852s+lzCA+/Ew=
        - I4zNz0X7zH0tHyrbu1RywVLLhrVae7V1zfgG2dXeQ5fIzU+WC/z2NQ1S8wkcEgzRhOPPD
          F1Y/3X/V4RB1ENKNelsRegMWrUu3eRYV/8JIumj4eGSnClTFoilT4DLbTjxGLAT0OtyXu
          mEF+bZl4d3LYIUckaWVw0nIAY66f4fxfhdRXwUO4VdMAvEz7YTD/53dHDvRwgAiGIRBbh
          4wuhmNDVOspahX9OpryvbZFt5pkIR+kvGYBOx/4DfJ44csHf3Dy937id6DzGw3bxJG0rR
          xoPJz/xA7HvjW4pBNb9nxUc6ZzcY2UV0P+STK/Utbe4TDtRAkBUvcU2ffUGELtm6meW3Z
          raKK0NkyO4UuyeMpiwLFHTnboGZfn9SUb3aQTpEMeZD6sJRsAXvzPmwTTI3uLsNEB1gcw
          8u5HEpkuGcW3kRPjoxpWRS1GUTpR3p3DpDj3NbywSo148AhxklUcr2SMiqlYqL36g8bSC
          O1gnU667zyQwZEcuzvh5vmyyor1qzUnZy2oW5pldzi2gDESmemUb8yyVpzkI9KFn4cLQ3
          3WmFVs8xAHYNRU5tUJuZ1dMw5vbsXynRZQjgdc7MNHqrgcsF+yWOYnwIOoCy3fJ8SnsfU
          H989G2F0kORXlvirqgDntVM8DVJcWXs6+n2SSqbMmu2nqCxwFxweX1gGp3/jOg=
        - fKTsN6+OSqUZ2u7Fk/VRY2QzyCKsxzPPXXT46RimruJf/wPXZUPdkCMKIYmi5uRvmaVgB
          xTLBcEGzVTP41hzfNnseLDH+/ZNoMnB7Vgr1u+VAbrZWmndnXF/4frYf+z8yVnFhO9QIY
          1MBnwySfMjieo9vTFc8ZgBpoi57d0uOIDXqfDZ4Ccot/qEQOR9mCz7Js5AM/vYlvxZb6P
          3F8pzrDsyQPWsE2kFzZRIyBxTfFX74c01tIKrc3zcH2wyFp1ywN+LBmOdryA4ihoelQi7
          lDXTucas8QHl17tUbOZU+AMU83c3zMNogHBlw3eKlexf7jM8raHIqil+ZkmI6+ymIMFFY
          m8B756zidjAOJxHltugZxyRWcH41gMgYr4yFnHxUUDuPzh3zvwsXEsYdSfkK5YSeNEBDy
          lW4uUjCNBgiTBU9fXP2O66no7evXFIXKTKYWd+guBdgJzQ+XIsStrne8wmZy3gi2zj348
          ej+/7/S17+x4XZe1dsn4OX2BWPFt0CP5pObn4pCnRBiKbeiFadx7V/yxMWaN2n8nRz0of
          CSf57K6vmcXmRIQdm7+rOOiVWRi5Mlct5LdWYre/KR57XuqZ98LrVGP5NtP+Zp8dxudaX
          jsPAdQIvhOQyLJoJhEpGkHkB0P1Qi/8sWHsG1ayWxn7WMoNMEUJLUdqdOtz2Nk=
        - h/+CIfWTCgxZVtTxRf9bNZlBmGlaZUpZ3flTs0DO/eCefwPUc3jN0rkRvkqdblO4BxEaH
          EcwIJSK94U36F7xj91Yx7vplCm0LTVwcdL1wWx9kTwM1ojeGDhhcGNLUUAJyblhS8vg55
          7kAoa6PfQ5/JS6oLkFQD9W/VmgA6rOUfF36EwFjZAdWk12oYNJNRpWnRn/pWIkq4cK7JT
          KD2KG/zGeKXSsuEaVJILORzuOvMI0+eLtEh3ngjNLm80EJccSpsoeuxBK/40FVv7eOpVU
          RK5DaibKygIb9AoP7PTiKgPJqrOkjESQPgX4C9lo+jGrsOJjcb/6UQeClrWD0oqsNB0bQ
          V6f2pziMYvzFSVJ1C92GP3aXAnaYicE7u+eWUE0ANrXJTlQhE+1qqrxP8zccuKf3MKFCO
          cX3eJEOZD2gt5aFGiEkvkVNc0eUyNV6WbkKHW+eHut3URs+yxbEx5YxS1p0sBw0Mlaux9
          bRpRhaw5G2GVdSdr+o4FShNUjJ4MIch7CGt4P3WBk/EWavTv/ElvAV0IgrFDTbxEy/hYF
          lyffJymBH9JvjTPy9hrEMioPgMMUpyH+M50tg/RyGIMI2mTiZkgwUyaRR8TIAaP3w61xW
          Lw+O9bjCbHbziCR28iOzaUq46lCC+NVW1zz+Y3PBg3vFH6CyeAU6WupK4P5oEo=
        - ZjgUMDhIQbPA9J57+cDdRjccX30Fnwxlsa0CDdF3FwMo9eyEIzQUIUcn8Eu8b4l1x8JYC
          G/755TDNeDB46g1SF0JdUGqyc0+28jctss+W6y3eXsiAR5M0j9HXcRtWuv/xojYiY1aDf
          6T88BtAKSlYINLynLiVdbDHQAiy5t3QLasLJGo2/df5eQ7BxxnBA3sbameWqLQ7I6nBOD
          Pq0RNGsjxNIS6cf1sYOKpiE8XiyI8ZenY1+Y6OoeqtVxPz1zHcHIhzmPQriJDfVZH30TM
          3IrjAlpEOHoJxRuLXqSXaiGCE1ndnqqHBc4fxS1TMfmSz1+BOCcEEAwuZlGYbDlWgR/wM
          ntzpUSEeSn96i0SbcvpAyId50k9kqkTgKJnc5Spqxh/f1T+Qlt677N3fS1CZtG4cbdqID
          b0Zo5OhvcQ/kKNfrRUlX4mpIyb2lWwMGAjV2wyh2mTeHRkBm3iYD7qH4haZaGYV+xxSrI
          +FXlNjtXZowijung5B/3/POhPCepz9+LGz6hNFSMCOiWnMptdjKYOeXfr3LMSvwWQwI0M
          ro5Bz3vG6o7CybzoxJ4LFqkgU2/Sp0v9w4kC7x+g3E6U5WNtvN9/wh4s4dA2dX0a0ynx+
          kio5TuPGcnSbpf0iQ5gI0iYgs+fbL85GNDMKkEdtN5ImdNAKQBJWaJUY6HmDKI=
        - AH5oPBul7HWJmqGN0bu2dscFISJCRI6o4Dz3Ge7sKiLMvdSOt6zV3HPPL6eNv7T849YbR
          ho1P620vf+DdzexcZFKbN8ZbDIWw4RGC1zBf5RlEEgmanhIekHJbppxXE9SmD4760KNrJ
          LTfJmBD3coyujbTkbfjjsiqDxfBA7kTAPzoYTO9eacVWwtZZbz3P/VAt5IAOlZ3Hog8Ha
          wHHJl+I1WjaGhfyFXXj2A+wcb9qp7bYzvLbho1ge1vTfGyfiu8136ygkEiatBn2xSLkDw
          DQ/i6QSiODotLFTB1q/hSmtce2Fd1K/9tp3RzQHYb3qg/TcrHjZ8j+LOF9XDaYf/P0JA4
          0xl5GMasqaPEKEnb58DfTFX4JLluOUhl7Dnm123BGDyYjZsRmoKFTLg9+DiYk3CHa/wGb
          ffhv9uYyygOfuHAE53e63+LuYqLaRJUFXcAbOYeoUXVX9eG0LnPaCQlZLJMYpbU70WhZc
          IPC2Cy3K3rKBLMCqRUEMkc5+hVh7WbJsBHHME+puKIi6klLRbdAr7zGw692hVlXK4OXlk
          Z4/ctpAogrWn7OfYx5rKuqe6GjYfrjUOZkIE+8hhqn4ICvsaP22e8jY/swZZmuKeSYKBZ
          lqBPasgZSHtGrfrvHvIG4FbFqrB/1GiosM9SSZG+nZ1TEGrKLRTgO3ecdk7x6g=

- semaphore:
    name: semaphore-e2e-tests
    max: 1

- job:
    name: e2e-tests-gardener
    pre-run: playbooks/pre.yml
    run: playbooks/run.yml
    # post-run: playbooks/post.yml
    # cleanup-run: playbooks/cleanup.yml
    secrets:
      - name: secret
        secret: SECRET_E2E_TESTS

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - yamllint
    post:
      jobs:
        - e2e-tests-gardener
