---
- secret:
    name: SECRET_E2E_TESTS
    data:
      OSCONFIG: !encrypted/pkcs1-oaep
        - EsD566aCjvM0ENXbGwX0InxvZP2zLrnB0Rq69TDEHXyZ7bU/uXWYEjN99IDagAk2FzSoV
          0JLdzQ+qIYszoe8O47UGngMWT23SzEKMpSW0Mc7OZuC8R8nrHTNmEuTqyJKxYwIKoCsKy
          9p8QTe8yoEcXTYreI/3nYz2cOc/reczQLEMmUnsXSahJtDg67G34MeNMxHJz++keDzVdl
          dNt+iYF+DwigkurJoO1aGcz2tCklfBs+KUUJUk294Ra3pqp+JtTFdh9QGwlolf/X0uDJo
          z08hVgNprLPtZJk37Zg9lhYv2yYtoR5QzewRioKJA/aUurz9VpweodwbPe6D+d6HCynEA
          MwMz2faC7hEa6ZLc0PKZBFTZLGFSDIFIg0O7KGSkr2rHz+i6LB93qUt9OfMfhcFH0/T/Q
          8BE1AlY+ZPI9rz8LnOH+ZbaMYT8p5RrPCXzNIlbCvJmnOR2cUDIVMjxu5f+yGjw6I5dPV
          Hp0ved5Ge938LqVJuijMT1Bhp2Iaxxn72MTuF3zKrnuujkrT4O8vDVdl+cD5HQdu7gVT4
          F3bEXc7ZmeT/QAC9x3nq1nXGeBxd1wJBcJJkUMFVx8rQQgAtU2Re+umjc5J9QtW1/VhIR
          NYtuZooy2RcyMqIkuitTWxA1i+P95P4XpC2jtFobnHoLAOFtEgKI3AWebxoFIQ=
      KUBECONFIG: !encrypted/pkcs1-oaep
        - MLsY+KfjeRZNXJhAPPuicTEyn50uvrhqp+qj3U4MF+iVYqaWXHLR63oc2KjGkyfKDyPPs
          dA1hghpgFCKEI6Wgor92mhhUbviDF+rwri4RiavHzqxJpmJdvzi+DhrP6GYecxIfaf4jz
          wij7Sv8gqH6NjLGHZ0fgCbFfPpEJM7DWMfRQB5djGnPaGwd/VMO62HaMcletU5O3vFwWV
          ugTRpdcILFTLrIBCq0wbURU4FDlB+MDBv61geKiZqrsIKE5NHyDI5WAeCdn0Rl/PvxP/t
          u9CkJ+zsFhDaFHSgy3zi7aZCkQUzIJpFHmKccuQxbdOjVOQrYKfozNFsTu0CPLPpjCJql
          Rh2LuzNN3kyAc8mf4ufnWDT/5Z3iAonw7lyh9tNM/85B0LHK6HdIo0n0PoYnzs7YMjQ+m
          DD4SXux0no75C0L5jFp+kC5/AlDLtSfQ4gDwRoYJlLtdmBCMMh7ffGizenKcc5DyZwXqw
          iWf7cbWgA5F76RfG9ogDy7cVjNLwwVg1/y9mVM6C6nllPOc1AB5Ig00my4orWUNlA6wnz
          wBkqsJApUbG4a9NobGMFKntrnWr3E4RfUwrSlMkKP4By7bJwu3/ucQp1SatoLChQ0lOLu
          +57ctzEQJ/psfKgBV/rfSJ7NWHOzApnJlhruVggrt0P7yxHDYePTchVIpyHZDs=
        - dB8mFajgcnm0z4Ei9DOAQTTGSCOCJiyNtw78iBZkE1W3emFjT8Dgk16pmnmKWn+jogLg2
          BjVzRQwM8XLVo1fFBaBy8xhj1+rfdcuU6ZpN6slo1r6zNDfh+nUo+fHorA/pCjXRqUPhS
          nTltY4ow31ST9xyffxeY9+s+3Vlk+DiPwroWgKUMA6o+yjPC41JFyAxVPzGn0GvpW+mfE
          0Rg5CoYWHm+Y1jeuatrG8NKN9L27027QKcSmDGtWPsmQB/bZosQVEF8iDQGQ5qruEuP7m
          9xT9dBsH3SIg+1mpeUQnoTplWCgx9LCNQAopG65LlJdClailnv+lZVjWtAZ8y2V1hkzKS
          2Leo3bKtIoRDnAGFvKrhuZeimoRc8RItWZYaPxu4J89bTwEs/JeIBbUmpaKKezURU65jG
          mY+uQ2zovICOPctUnSVlBpN49LxLcnO2quOKvMBK9Yi0nuhIQwXTKdFwlZ8ZGYkV7ztG/
          osyqoidd7Nbx2qgtGpTME6iZYhZ2Yp/kTC+sEYRsp0JgNWkCPHHjG42WNaiVheq4ntZD9
          LRGnE14gOmFOMjH2YxTxuM4RrpQVC0iBQRlCir09IYoTiBJ7t3h4lY3JaKsKzvjtiiZyB
          RcCO9HniJmWEOVI8tiPNMbTBAUXlyEGTE5Sb8Mz5UFdVy79JJG+o2yB4PkeaAA=
        - BU6XwpDnYMQN5sX2Q82AjuSCKEiFi4S5swMPjVGxUnSBdh+ZMl+zQqi7Hkvawh0QvNlDr
          LXRGOiwsihG3pOS9HyUb5/nLp4Wx8B7TsSSvHCF1VHIlM28k4V/KNIbpNdaNzz/opEVTg
          dBxyMcW3shBrCEuwtnBwrHcdK6JNIk5mM5zy18Ac38tFCXXgpnRPd8ge6c60x3XAY3q/Y
          lDv1JTpM2nt1bDTKA4ZFoY37O89u/UDv0Bw9lpHWA+DWJSPxhhLXFMhDklylrt0vvz8cU
          eoBLHO6UVSDwZ8YK6GzBR8kVN927VrrWn14mCmTNLrVdPntlNbJgGZ8kbMqzN5EWuli0c
          OppzOBYx9SVzR+6m/ogljx9uzYw4LSEJQPDWtsWiVcQxXpQ3QdauL9qyvcUwLfJgXmpN7
          7iUzrw31C0NUIvYiRCNjtQJ7mTbxUgBJVTlLtBNrBg8ROgE82SP0T9ujsrL2MN4FP+w3q
          5+AF4j9jEuyeT21zOCKGhNKkjF11W9Pn52t7etcXLkVq/Osj4sHKYmGBLFUFeKybtcILX
          OUHHip2So7sbdLe/CHJLlsxqShMkGZy8Fw5w+8PI8ZSb64d98Xu1y/tlrxsQmMIsTTd4z
          6RIfL8sCZvcC4viy2ISo2ns2ICD+pXfS2FS7ccwQWN35jSb285LOtNE+sQ35yc=
        - kZDISNDEXziKgH15AogshSAEUF5vWY/r2Zm6JRyouYTDDszJm5PpjSWAsqZfiXQqU5kn3
          N6OKM4+bkuFe8IPYRELZe07PC/RlQx+297D1d6cfb8Yoa/vEKH+f+awaLKKIJkE9ZVc3S
          KrriN6sLNUtvxPZwgXbQ7zSHkqQV5mDgsKPKAOu9WV2fh7IagH2vutdk/OsKI8jYXcum9
          iWyBonCiyAvGqwv1NXoI5VDpjjaM9h2yeg3TdCKGxat8E4MiKZSCEkay6+hz04Nf+TUcQ
          cgRxUxOyU+n91tKlz+cb8A7/xf+gIWRgOGqozkO4+5clHnbmOo0J9tNepacDjlFSpqgcZ
          HVVeG//aESMffq+uUac/lZ7UHmQEyUEpTzSsI82yH3wnobE3tmnVAI+21GIKSh8WWvDdF
          7ziuh/4OvtBlzoLMeM4o068f+E3xM26yhLwirPoBIJ22IRsmJNOjK3a4wLeOfAMLblO5v
          2ArKFWGLu4Tl4VG+B+r/eGdzQrLGpi6QKZ/8hwQF/BcAyvYJIUTGaKjCnKEb0suGoDOTv
          EWisjTvwagRtSO+UT9WFi7wdQidXqtyS4c/toXJ7Y1Gp9MM9aP8Goh5cy/LTSEXryI9nq
          DWfCBqETBwYM1LHQRGKe4xE7hA0nOwE9Xg9bn032rCWe2ugPVa0sZOxZ1jF03c=
        - ZxufVjJaGCUdQgGF7+Yb8fFw0YTBy8gbKIVlrAmihnBbef2xowJBSLyTloS4GmIPnJ5N3
          Br+1/ftvnZg5dOPvVKrn0XxToWNUKRInjabR5tfkMy44JZtWhb0W7CZgppLt0O/AnFbS1
          xskTTOXqct8SfK+O6tp9tYakQUmzlqBf0gqxlWLr5TGF0dX09Dl23ybPaUoZpJhmalC89
          8deBxCbMiE59+SgQnOSd2LI/ccNA9Tuv1SclzZh8BPoZaivBP0/wWFuHPBeKdkuSXUvk1
          rozgIuAjZBuqYVEbHtesjxWBzPbRK+5m88PISt9raJVi4tbaf/o5TIbfKRhgjKczIVpTu
          TZMwG1WZaVLtKUZVNaiMTNLN2/A6bBwtXlmDXqcO86RsPu4fpF3ipz2YqH0/Yxv960CSy
          lVhwajje6eTqv1pncFKI+89V+k3LShn7RSqUPdgxetKnh2YFH9nV2q4q0yZjTdm8SMkIb
          yipbkU9tJd58shU/9DccqNEgd9YGxSPastWNU97LR5Bp6EdCV4HYiQWDQKnuOuM1vSMfe
          1YzyClng7I7v1IvwImV+LfWFX7aEwJn4Ie4kl3NtQGYT1Z8cHq3J5RlMQeACwnOMfv+XX
          SZ1FjLyqykSgtkG/ah7X2xuaHzoyUKwl0h8ksL27y6ussqD32BpMYVaHCMO7Hw=
        - SfroVBSmyupK9STQYvDPp3mgIV4ufX6iXtMH14Ga61XdlfIi2Z1h0wlDYgYH7jeMrDPav
          EYDhDm0Xdn3OIoic3r19n1bMsUn1NjpcIeVF5xPMn8nmvlnizWAysRyvSdB5Io/bAlrIF
          wDBK7iAIgflJOOvsodmg07tO+qQe6WhJyFqiU0KpEoArXVr2cyEnZO1k51qoT+YJdutYW
          0G4huVQM9UMbTAv2GedvRSsFkyIDRuCRynMrZW/3rxy9cBZ202XHzI0ytRbISAko55i+3
          ZDFQucZ5eHjlWd1db6gMaJ05kuVp/h31VkC+oAV4Zj8Ezy6IZ3gc9QDXU/NfX3mgBhLaQ
          AqkcqHCF5VvDYuZNR+LJtpa45CpmLVZrAqEmtAdBI+xbFJ0XAK5pM69C8JU6a45ObP4Dl
          bK+t2MmHaUH+D2zQv2uc9kob983Sd7XIld0wMo7+PdNjgcZ9R3EqNQmQDubKrMpegkvWB
          pLFOWLm1lEZ0OIOf5U/WN2k8FsTjW4lzdTHbrOb/ohMY8TnOvfOuJZIigkS/xPWJ1wP8r
          mSG43/SHdPDQEpCFkRoN2SXVu430G1hlnTZQ9aVz/KIBcuWwVNvrkNXkIdyNGWkVFdq8H
          bOLH9wE/ncaEV/UYVU3CwYDy3oWHhTAuQzP+c3ai9qgTEXwA8006AEzHFb8qNA=

- semaphore:
    name: semaphore-e2e-tests-gardener
    max: 4

- semaphore:
    name: semaphore-e2e-tests-openstack
    max: 1

- job:
    name: e2e-tests-gardener
    abstract: true
    pre-run: playbooks/gardener/pre.yml
    run: playbooks/gardener/run.yml
    post-run: playbooks/gardener/post.yml
    timeout: 14400
    secrets:
      - name: secret
        secret: SECRET_E2E_TESTS
    semaphores:
      - name: semaphore-e2e-tests-gardener

- job:
    name: e2e-tests-openstack
    pre-run: playbooks/openstack/pre.yml
    run: playbooks/openstack/run.yml
    post-run: playbooks/openstack/post.yml
    secrets:
      - name: secret
        secret: SECRET_E2E_TESTS
    semaphores:
      - name: semaphore-e2e-tests-openstack

- job:
    name: e2e-tests-gardener-1.27-quick
    parent: e2e-tests-gardener
    vars:
      kubernetes_version: "1.27.10"
      sonobuoy_mode: quick

- job:
    name: e2e-tests-gardener-1.28-quick
    parent: e2e-tests-gardener
    vars:
      kubernetes_version: "1.28.6"
      sonobuoy_mode: quick

- job:
    name: e2e-tests-gardener-1.27-calico
    parent: e2e-tests-gardener
    vars:
      kubernetes_version: "1.27.10"
      networking_type: calico

- job:
    name: e2e-tests-gardener-1.28-calico
    parent: e2e-tests-gardener
    vars:
      kubernetes_version: "1.28.6"
      networking_type: calico

- job:
    name: e2e-tests-gardener-1.27-cilium
    parent: e2e-tests-gardener
    vars:
      kubernetes_version: "1.27.10"
      networking_type: cilium

- job:
    name: e2e-tests-gardener-1.28-cilium
    parent: e2e-tests-gardener
    vars:
      kubernetes_version: "1.28.6"
      networking_type: cilium

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - yamllint
    post:
      jobs:
        - e2e-tests-gardener-1.27-quick
        - e2e-tests-gardener-1.28-quick
        - e2e-tests-openstack
    periodic-hourly:
      jobs:
        - e2e-tests-gardener-1.27-quick
        - e2e-tests-gardener-1.28-quick
        - e2e-tests-openstack
    periodic-daily:
      jobs:
        - e2e-tests-gardener-1.27-calico
        - e2e-tests-gardener-1.28-calico
        - e2e-tests-gardener-1.27-cilium
        - e2e-tests-gardener-1.28-cilium
