---
- secret:
    name: SECRET_E2E_TESTS
    data:
      OSCONFIG: !encrypted/pkcs1-oaep
        - EsD566aCjvM0ENXbGwX0InxvZP2zLrnB0Rq69TDEHXyZ7bU/uXWYEjN99IDagAk2FzSoV
          0JLdzQ+qIYszoe8O47UGngMWT23SzEKMpSW0Mc7OZuC8R8nrHTNmEuTqyJKxYwIKoCsKy
          9p8QTe8yoEcXTYreI/3nYz2cOc/reczQLEMmUnsXSahJtDg67G34MeNMxHJz++keDzVdl
          dNt+iYF+DwigkurJoO1aGcz2tCklfBs+KUUJUk294Ra3pqp+JtTFdh9QGwlolf/X0uDJo
          z08hVgNprLPtZJk37Zg9lhYv2yYtoR5QzewRioKJA/aUurz9VpweodwbPe6D+d6HCynEA
          MwMz2faC7hEa6ZLc0PKZBFTZLGFSDIFIg0O7KGSkr2rHz+i6LB93qUt9OfMfhcFH0/T/Q
          8BE1AlY+ZPI9rz8LnOH+ZbaMYT8p5RrPCXzNIlbCvJmnOR2cUDIVMjxu5f+yGjw6I5dPV
          Hp0ved5Ge938LqVJuijMT1Bhp2Iaxxn72MTuF3zKrnuujkrT4O8vDVdl+cD5HQdu7gVT4
          F3bEXc7ZmeT/QAC9x3nq1nXGeBxd1wJBcJJkUMFVx8rQQgAtU2Re+umjc5J9QtW1/VhIR
          NYtuZooy2RcyMqIkuitTWxA1i+P95P4XpC2jtFobnHoLAOFtEgKI3AWebxoFIQ=
      KUBECONFIG: !encrypted/pkcs1-oaep
        - jpu6jYOp6uFtbqDaAFgvIbg1W3bEFpyVjspavPf62Dr8w8PSZpKlHB2DT6UYnTGRWnKoR
          bIXSdpq3P5fo3tNKZYLSPzW9id5isP4EUoiM7Hg3L7yHxF+XKtPCLLe75DFwi2w2L/yd5
          yBspUlLCdLkn7ZdpNTLDntzDMVCx/TKT88toP0OxGPlKETLQLq1LVtuYCuC0wgoeRlK+5
          aAO2ssCmLvnDPzjvvaAat0rWhukEJE9pt7ZVMEvgFwb5hM0bbbbgy9/IyH7XOcSAotxC4
          FS9H3eTxW/HyNk2u0jwqedw3Pdw8UhJa7CTKX/ei5SeGIfvEfVs12cO5e0l9T7gF59tln
          tl2XKjbZlIl2co7R11wBN2rBcI6zLKIFLqBZmhMwqUqwf2EQflpF1zYW2z5HogY4gfzLb
          /SMqnDazccuZ4FUPYJwPrYPKAFegBFHndd6WgWzDqCwpuHZiJCtqZleE/eKAYvwLtUNX/
          u1BYJOcvakP520J1kEoCoV0s3WbU1tJPyTFl4oIVkIulHSX4PZuDQ5JtPXixGqAelC1t8
          m8NNAXe+YF9JCHMssLJKig+Zds+tFNsao2Rwyx2s6Jc/jcnESF5iO7akQ977c4AkzQ/4R
          uJ1OEnzz+QU/8PdMYFTxX1opZMKtvNhySK6G2SuiCqq2tobwzhUdHcMI7afLUg=
        - giBDqI5xXsI753wh1eSmFjhckTE5Lr2SLG2u3fw+4xNx7ctnNEn3Pf2SO34t6wiwrxr3M
          fGRT7U3JL+eUsA17KfmPB/nOAzw0Ti8ykVap9r5zegCiSgIsZ9GpqdJ9C8Lj1+a0QIN3B
          tFsamThFTU+L9BMICebU3y0A7SZ4IjyV/tgjPwSfy6oQJvsm9Ku1/gfrr7jfalzvmTs17
          6tv06kjGTPfWYQ5Tz/N3LfxziPwJDphw+blLL1pzGvbptnIXU8Z60+pp4w1qZ67tV0JTY
          1//cBBiUJJEEep0STdufCP0WxV44RepZWZHc84txS0dQY7Xl4YgjPux5EekkuYmIinsWx
          4vWpKs6GO4EW16BdCpG8JLlKMVDgbFgJvWDQx+1madp6xn2TDlSDz3EikMLNVVUnOrPPT
          dyA0c62SEa7PCd+cu79lVuEcjE6wgZpuQv6N9jVUVUW3AewcV73rZTiu1yXwthT/+T2Ah
          +oibDchGdhlXGi6fLuDtrcm0YY82UQD0R6F39BY4MtYSa0YF/BwN6ogMOan+j/IazYoSh
          6Rad3Jt77UBt/6Av67J4vZMeKjDTkz5ZRDM56ZrG0dqRVnBrpyrbk+hVolV/AV/0543ad
          89YUKBPlRA72VEKvtHzeWlZgaj2vtGu6qapxE2w9oa7MJpncQ1r2AunR+pYZBs=
        - iuEqgHiAkG/8PONOka6JH8cnbdO4HAjUWgldp8wv3t7qcxkXIt2p01Zhd4Guoh9c5COIK
          bDWU6XizJTGxHF1d+wBBbLYRgKV3/L+ULMpwsoMUHLmADa6p95Vx8FL9WeyyTlrVbCQ0V
          G7vW1asfdS0HBRaaxAnHC8vwt8QanrHe/LcLRPORj30HXERGE6mw2wQhN3GII3UiPNPM6
          8afBzeXQTB34g7G8veCatxl+F+ItJL3C+MoKGbBUybmHLUd5QrHvgu7X0aIMs8yCRS70A
          8XF+I3nvj0Q+JLPmLYdM/zFVmvtBQjlPirYFJ/YHUo92TJqJrswcVWde2dKNACd1YT31x
          kyUOW4Z8eRlmsmiJoACjYOMnt/1k1+JuFf/rcfA/W4z4O3Bczx3lDkIXQXMU95Qm6xaou
          EyS9laS0zU0/OVF9dz1aOwDbS3Q6ZN6TpoqdRUzAHL6gEQTKvCtggtS0bKDxW5AQoEQPI
          QCHRddFsTQIDW4FR3bytDH73Ziftf3is0LHm1kpcZcte0KwD8/yOiFEnOegbM6S5DYAMr
          GFRGZKweCzPQbSYjpTS8sNTnqaxzvYCoLRhjuCz3C24LOT9JkkW1Oz3Ld7n0smCS6ruXq
          x8441AeRSIyCS3YSfwJIkx100/VdJ7uyqVaLIgzF1MZmsBeHOw0lOFCOqwlNIU=
        - PUOs+rtL7eg8cPDpBH8Gh3h7N1s50pg0tCsmC06HYnJ0Aku97/2o47uwlRX5XO4Pw90ct
          r2HO7oEZVZAJP60VYayzFxqtFQKtJ0fNTSdejo6K6Jez7y973gjQphIMZ09Z/L3GAZWIt
          lL8b5qZ5q7qv8hdo8oEr6O1v07abD+IG0kDcOoYzJ7LJR9+ckhl2aXj5W54g2L+IJUFOO
          59tdeuihBYnsTo8n4NsiUyNG7he9vCQF/XOXURuWYEUjJ/2lz8OkU5PtGcOmeB+M68waY
          o4FCaZCqmjJQ7noAVJO//H4lQmvJmQXc7syuWMp+2vApBb9KKHEzAyDhjVMsrBK8nlaEr
          KfiDALD2NGgtngI7nnuleBrfJCmBYOt/8XKZYpg88WKqEyCUeXxROfBA5hEkgsNvRnwle
          JJ1H31XvF5Vh4OK9ZhGipVgzhIyNTBypVpbn2MsOetOGU539QdCahqgp+4qdhnP6QLEQE
          LpykZBu0UEIJunZJdFc1NrYBErhFP6M2hP2B6D2C8GMyRdKfjuhig5y5GSWgZXRMPJQGq
          a1G6KKmSAmgxDi4uJ5io80YWiwM1JVYgIa0XHu63/2sPfwpVLdQc5QG8M8tG/PHgsa/DH
          BnoD2XZRFNhd9zFrJ9W0QBcvjsXE6jw6hvfpdCOF/z6Oqw44cXh/zp2pTLErCM=
        - M2OAZlutUnVzZgtWEcFTxDQcHvMyyrYXJjFG2ADY1cgG7mILV4lCrZDe6vEdzuXESWOP3
          dYOrbbUjCHStselwkTBZsGMdjVryogKUW9uSuYCqsu6gZi3n6sRhj2j30+5HYcScL8qI8
          ICUaPJtRKe5GweAP6EmhbCmwkLoX6GthgyULoskMoEepeqv1tiSJMaCyX/A/sFNnheUSg
          kGslJIFYfr2JzMXKq7ozALsJBxTjOFHjpSPPOfav9zLLUORIptfAkYzc1O+m9mgb1TBnM
          dTKCJ31AxDdBR76PKEuizLWjKCyFREcfwk2SRN6rNc0KPqeWwECZSupZIvdexeckVfRTT
          pJBZE98QmIjvd1/bcvZyznD8TQbzDiLbeHbDbKNExKc0FhyQwiD2+Eyb3YGEVqa5c0QeM
          3Jb8fnlxmYRxKgJpRJCDM1+8sWZQDINXs/HETLtoMqsOswYhagzOSb7H80X7VmGmGkEGS
          B0vXHf/zQBQjnWCEPBEWpgNHSgRPK0UYVGPT5SDo90FmPsn4Zxrc+HUcpaOf84H0emMJp
          0nUVU5seShcdtBci77RmJQDQV58WMGcfGYw6guCtQXJXMFiTMMmwM56ZUfTjKsOscm5LN
          3UP1l3JytkhuT35QzgzcQhqmCU8YO2Wl25qos45/OMqle7Bdxle84BoWb7KJqI=
        - STDIzsoaDcprsbpftR6cyLqmaDSy+uPEOn6D6P9eMidbE6f8VaAHs/oWEY5tud/675tHg
          Iz01pYBpztywz2r/f3GoDnX2EJZYEgyTyPniRVdlP7ahbRS1uE6QenZ7DIDEu6DCMk1ph
          FC2zbgphm0iCX/toNw4rRD5lD2C8nP7ucVlAyieueX8nXpDuPrLId2/3swsXDD9FrBrl8
          /uJUuI/g/uFQ3/HK18SAJFSfmEtkaYdl9/sZmWAGskvxQE67jqkBhfo7NXGKBnE7ZsbEo
          PnAyVEdegZ3ToEPMCPEO0w+I117XAgI2GQlRee7IFEzHfIECgOMY7T0HNiQkBUyCK5QLJ
          rVL3zn4Rb7KgcCDixKjUwjimZc5F2b4pls5VWvZ/D1BWTW4yv0r8TyXS+J3iNipj0leA7
          navWWiOWO14T7BKLhXANtBgHsJFB6Wps6pbRA/ZuEwq+BusGY4wpzQ76eYbtzQPxzW4kn
          y98/18OPqzNJOtHpH4Sv2QpXvHE0Jg5IXcbZYakHx05hryWfqM7kOik7sv5jdyIH0kfTt
          K15VLZRR5ay7SavIuKZxz++bMoVSGngZ7Oxk9w/a66yFaIodiV0IW2AXU8rHcOsNAZ90T
          fUzv4agCKjqYAYUbmJFajrKh6XbOk4Gwk1Go6uDVxMfCmYMAn9HNWWCol5P7Ho=

- semaphore:
    name: semaphore-e2e-tests-gardener
    max: 4

- semaphore:
    name: semaphore-e2e-tests-openstack
    max: 1

- job:
    name: e2e-tests-gardener
    abstract: true
    pre-run: playbooks/gardener/pre.yml
    run: playbooks/gardener/run.yml
    post-run: playbooks/gardener/post.yml
    timeout: 14400
    secrets:
      - name: secret
        secret: SECRET_E2E_TESTS
    semaphores:
      - name: semaphore-e2e-tests-gardener

- job:
    name: e2e-tests-openstack
    pre-run: playbooks/openstack/pre.yml
    run: playbooks/openstack/run.yml
    post-run: playbooks/openstack/post.yml
    secrets:
      - name: secret
        secret: SECRET_E2E_TESTS
    semaphores:
      - name: semaphore-e2e-tests-openstack

- job:
    name: e2e-tests-gardener-1.29-quick
    parent: e2e-tests-gardener
    vars:
      kubernetes_version: "1.29"
      sonobuoy_mode: quick

- job:
    name: e2e-tests-gardener-1.29-calico
    parent: e2e-tests-gardener
    vars:
      kubernetes_version: "1.29"
      networking_type: calico

- job:
    name: e2e-tests-gardener-1.29-cilium
    parent: e2e-tests-gardener
    vars:
      kubernetes_version: "1.29"
      networking_type: cilium

- job:
    name: e2e-tests-gardener-1.30-quick
    parent: e2e-tests-gardener
    vars:
      kubernetes_version: "1.30"
      sonobuoy_mode: quick

- job:
    name: e2e-tests-gardener-1.30-calico
    parent: e2e-tests-gardener
    vars:
      kubernetes_version: "1.30"
      networking_type: calico

- job:
    name: e2e-tests-gardener-1.30-cilium
    parent: e2e-tests-gardener
    vars:
      kubernetes_version: "1.30"
      networking_type: cilium

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - yamllint
    post:
      jobs:
        - e2e-tests-gardener-1.29-quick
        - e2e-tests-gardener-1.30-quick
        - e2e-tests-openstack
    periodic-hourly:
      jobs:
        # - e2e-tests-gardener-1.29-quick
        - e2e-tests-openstack
    # periodic-daily:
    #   jobs:
    #     - e2e-tests-gardener-1.29-calico
    #     - e2e-tests-gardener-1.29-cilium
