---
- name: Run play
  hosts: all

  vars:
    inner_name: "{{ zuul.build[:8] }}"

  roles:
    - role: tox
      vars:
        tox_extra_args: "-- --parallel 5 --number 10 --prefix {{ inner_name }} --volume --no-delete"
        zuul_work_dir: "{{ ansible_user_dir }}/openstack-simple-stress"
