---
- name: Post play
  hosts: all

  vars:
    kubectl_binary: kubectl

  tasks:
    - name: Run post script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}/gardener"
        cmd: |
          set -e
          set -o pipefail
          set -x

          export KUBECONFIG=kubeconfig.yaml

          {{ kubectl_binary }} annotate confirmation.gardener.cloud/deletion=true -f deployment.yaml
          {{ kubectl_binary }} delete -f deployment.yaml
      changed_when: false
