---
- name: Post play
  hosts: all

  vars:
    kubectl_binary: kubectl

    inner_cloud_profile: "{{ cloud_profile | default('regio-a') }}"
    inner_kubernetes_series: "{{ kubernetes_version | default('1.27') }}"

  tasks:
    - name: Run post script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}/gardener"
        cmd: |
          set -e
          set -o pipefail
          set -x

          export KUBECONFIG=kubeconfig.yaml

          {{ kubectl_binary }} annotate confirmation.gardener.cloud/deletion=true -f {{ inner_cloud_profile }}/{{ inner_kubernetes_series }}/deployment.yaml
          {{ kubectl_binary }} delete -f {{ inner_cloud_profile }}/{{ inner_kubernetes_series }}/deployment.yaml
      changed_when: false
