---
- name: Pre play
  hosts: all

  tasks:
    - name: Copy kubeconfig.yaml configuration file
      no_log: true
      ansible.builtin.copy:
        content: "{{ secret.KUBECONFIG }}"
        dest: "{{ zuul.project.src_dir }}/gardener/kubeconfig.yaml"
        remote_src: true
        mode: '0600'
        owner: zuul
        group: zuul

    - name: Run pre script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}/gardener"
        cmd: |
          set -e
          set -o pipefail
          set -x

          source versions.sh
          source binaries.sh

          # install sonobuyo
          wget https://github.com/vmware-tanzu/sonobuoy/releases/download/v${SONOBUOY_VERSION}/sonobuoy_${SONOBUOY_VERSION}_linux_amd64.tar.gz
          tar xvzf sonobuoy_${SONOBUOY_VERSION}_linux_amd64.tar.gz sonobuoy
          rm sonobuoy_${SONOBUOY_VERSION}_linux_amd64.tar.gz

          # install gardenlogin
          wget https://github.com/gardener/gardenlogin/releases/download/v${GARDENLOGIN_VERSION}/gardenlogin_linux_amd64
          mv gardenlogin_linux_amd64 gardenlogin
          chmod + gardenlogin

          # install gardenctl
          wget https://github.com/gardener/gardenctl-v2/releases/download/v${GARDENCTL_VERSION}/gardenctl_v2_linux_amd64
          mv gardenctl_v2_linux_amd64 gardenctl
          chmod +x gardenctl

          # install kubectl
          curl -LO https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
          chmod +x kubectl

          # install krew
          wget https://github.com/kubernetes-sigs/krew/releases/download/v${KREW_VERSION}/krew-linux_amd64.tar.gz
          tar xvzf krew-linux_amd64.tar.gz
          rm krew-linux_amd64.tar.gz LICENSE
          mv krew-linux_amd64 krew
          chmod +x krew
          krew install krew

          # install oidc-login plugin
          # kubectl krew install oidc-login

          # prepare e2e garden
          [ -n "$GCTL_SESSION_ID" ] || [ -n "$TERM_SESSION_ID" ] || export GCTL_SESSION_ID=$(uuidgen)
          $GARDENCTL --config gardenctl.yaml config set-garden e2e --kubeconfig kubeconfig.yaml

      changed_when: false
