---
- name: Pre play
  hosts: all

  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.apt:
        name:
          - jq
        update_cache: true
        state: present

    - name: Copy kubeconfig.yaml configuration file
      ansible.builtin.copy:
        content: "{{ secret.KUBECONFIG }}"
        dest: "{{ zuul.project.src_dir }}/gardener/kubeconfig.yaml"
        remote_src: true
        mode: '0600'
        owner: zuul
        group: zuul

    - name: Run pre script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}/gardener"
        cmd: |
          set -e
          set -o pipefail
          set -x

          source versions.sh
          source binaries.sh

          # install sonobuyo
          wget https://github.com/vmware-tanzu/sonobuoy/releases/download/v${SONOBUOY_VERSION}/sonobuoy_${SONOBUOY_VERSION}_linux_amd64.tar.gz
          tar xvzf sonobuoy_${SONOBUOY_VERSION}_linux_amd64.tar.gz sonobuoy
          rm sonobuoy_${SONOBUOY_VERSION}_linux_amd64.tar.gz

          # install gardenlogin
          wget https://github.com/gardener/gardenlogin/releases/download/v${GARDENLOGIN_VERSION}/gardenlogin_linux_amd64
          mv gardenlogin_linux_amd64 gardenlogin
          chmod + gardenlogin
          sudo mv gardenlogin /usr/local/bin/gardenlogin
          sudo ln -s /usr/local/bin/gardenlogin /usr/local/bin/kubectl-gardenlogin

          # install gardenctl
          wget https://github.com/gardener/gardenctl-v2/releases/download/v${GARDENCTL_VERSION}/gardenctl_v2_linux_amd64
          mv gardenctl_v2_linux_amd64 gardenctl
          chmod +x gardenctl
          sudo mv gardenctl /usr/local/bin/gardenctl

          # install kubectl
          curl -LO https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

          # prepare e2e garden
          [ -n "$GCTL_SESSION_ID" ] || [ -n "$TERM_SESSION_ID" ] || export GCTL_SESSION_ID=$(uuidgen)
          $GARDENCTL config set-garden e2e --kubeconfig kubeconfig.yaml

      changed_when: false
