---
- name: Run play
  hosts: all

  tasks:
    - name: Run run script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}/gardener"
        cmd: |
          set -e
          set -o pipefail
          set -x

          source binaries.sh
          source configuration.sh

          $KUBECTL get shoots

      changed_when: false
