---
- name: Run play
  hosts: all

  vars:
    gardenctl_binary: gardenctl
    sonobuoy_binary: sonobuoy

  tasks:
    - name: Run run script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}/gardener"
        cmd: |
          set -e
          set -o pipefail
          set -x

          [ -n "$GCTL_SESSION_ID" ] || [ -n "$TERM_SESSION_ID" ] || export GCTL_SESSION_ID=$(uuidgen)
          eval $({{ gardenctl_binary }} kubectl-env bash)

          {{ sonobuoy_binary }} run --mode certified-conformance --wait --wait-output progress
          results=$({{ sonobuoy_binary }} retrieve)
          {{ sonobuoy_binary }} results $results
      changed_when: false
