---
- name: Run play
  hosts: all

  vars:
    gardenctl_binary: gardenctl
    sonobuoy_binary: sonobuoy

    inner_cloud_profile: "{{ cloud_profile | default('regio-a') }}"
    inner_project_name: "{{ project_name | default('cruv4yqhsc') }}"
    inner_sonobuoy_mode: "{{ sonobuoy_mode | default('certified-conformance') }}"

  tasks:
    - name: Run run script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}/gardener"
        cmd: |
          set -e
          set -o pipefail
          set -x

          export KUBECONFIG=kubeconfig.yaml

          [ -n "$GCTL_SESSION_ID" ] || [ -n "$TERM_SESSION_ID" ] || export GCTL_SESSION_ID=$(uuidgen)
          {{ gardenctl_binary }} target --garden e2e --project {{ inner_project_name }} --shoot {{ inner_cloud_profile }}
          eval $({{ gardenctl_binary }} kubectl-env bash)

          {{ sonobuoy_binary }} delete --wait
          {{ sonobuoy_binary }} run --mode {{ inner_sonobuoy_mode }} --wait --wait-output progress
          results=$({{ sonobuoy_binary }} retrieve)
          {{ sonobuoy_binary }} results $results
      changed_when: false
