---
- name: Run play
  hosts: all

  tasks:
    - name: Run run script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}/gardener"
        cmd: |
          set -e
          set -o pipefail
          set -x

          source binaries.sh
          source configuration.sh

          $KUBECTL apply -f regio-a/deployment.yaml

          while [[ $($KUBECTL get shoots regio-a -o json | jq -r '.metadata.labels["shoot.gardener.cloud/status"]') != "healthy" ]]; do
              echo "$(date) - waiting for shoot"
              sleep 10
          done

          while [[ $($KUBECTL get shoots regio-a -o json | jq -r '.status.conditions | .[].status' | xargs -n1 -I {} bash -c "if [[ '{}' != True ]]; then echo False; fi")  =~ False ]]; do
              echo "$(date) - waiting for shoot"
              sleep 10
          done

          $KUBECTL get shoots

          [ -n "$GCTL_SESSION_ID" ] || [ -n "$TERM_SESSION_ID" ] || export GCTL_SESSION_ID=$(uuidgen)
          $GARDENCTL target --garden e2e --project cruv4yqhsc --shoot regio-a
          eval $($GARDENCTL kubectl-env bash)
          $KUBECTL get nodes
      changed_when: false
