---
- name: Run play
  hosts: all

  vars:
    sonobuoy_binary: sonobuoy

    inner_cloud_profile: "{{ cloud_profile | default('regio-a') }}"
    inner_kubernetes_series: "{{ kubernetes_version | default('1.27') }}"

  tasks:
    - name: Run run script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}/gardener"
        cmd: |
          set -e
          set -o pipefail
          set -x

          export KUBECONFIG=kubeconfig.yaml

          {{ sonobuoy_binary }} run --mode certified-conformance --wait --wait-output progress
          results=$({{ sonobuoy_binary }} retrieve)
          {{ sonobuoy_binary }} results $results
      changed_when: false
